version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql-gp
    restart: on-failure
    volumes:
      - /c/NL-POC/backend/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: mydb
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: root
      MYSQL_ROOT_USER: root
      # You can use whatever password you like
      MYSQL_PASSWORD: Password
      # Password for root access
      MYSQL_ROOT_PASSWORD: Password
      #MYSQL_ROOT_HOST: localhost
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - Network_apps

  be:
    image: backend2022:latest
    depends_on:
      - db
    restart: on-failure
    tty: true
    container_name: backend2022
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-gp:3306/mydb
    networks:
      - Network_apps
  ui:
    image: frontendimage-prod-5
    depends_on:
      - be
    restart: on-failure
    tty: true
    container_name: frontend-p5
    ports:
      - 3000:80
    networks:
      - Network_apps
networks:
  Network_apps:
